version: "3"

services:
  postgresql:
    container_name: 'homeland_postgresql'
    image: postgres:9.5-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data

  redis:
    container_name: 'homeland_redis'
    image: redis:3.2.7-alpine
    ports:
      - '6379:6379'
    volumes:
      - ./data/redis:/data
      - ./etc/redis.conf:/etc/redis.conf
    command: redis-server /etc/redis.conf --maxmemory 400mb

  elasticsearch:
    container_name: 'homeland_elasticsearch'
    image: elasticsearch:5-alpine
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx512m"
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - '9200'
      - '9300'

  app: &app_base
    container_name: 'homeland_app'
    image: homeland/homeland:${IMAGE_VERSION:-latest}
    env_file:
      - app.secret.env
      - app.local.env
    links:
      - elasticsearch
      - postgresql
      - redis
    logging:
      options:
        max-size: "1g"
        max-file: "10"
    volumes:
      - ./data/uploads:/home/app/homeland/public/uploads
      - ./a-nkn-tmp/shared/.well-known:/home/app/homeland/public/.well-known
      - ./a-nkn-tmp/shared/cache/uploads-thumb:/home/app/cache/uploads-thumb
      - ./a-nkn-tmp/shared/system:/home/app/homeland/public/system
      - ./a-nkn-tmp/shared/ssl:/home/app/ssl
      - ./a-nkn-tmp/log:/home/app/log
      - ./a-nkn-tmp/tmp/pids:/home/app/pids
      - ./a-nkn-tmp/log:/home/app/homeland/log
      - ./a-nkn-tmp/tmp:/home/app/homeland/tmp
      # - ./etc/nginx/conf.d:/etc/nginx/conf.d
      #
      - ./a-nkn-dev/homeland/config/nginx/conf.d:/etc/nginx/conf.d
      - ./a-nkn-dev/homeland/config/nginx/homeland.conf.erb:/etc/nginx/homeland.conf.erb
      - ./a-nkn-dev/homeland/config/nginx/ssl.conf:/etc/nginx/ssl.conf
      - ./a-nkn-dev/homeland/app:/home/app/homeland/app
      - ./a-nkn-dev/homeland/public/tools:/home/app/homeland/public/tools
      - ./a-nkn-dev/homeland/public/favicon.ico:/home/app/homeland/public/favicon.ico
      - ./a-nkn-dev/homeland/public/robots.txt:/home/app/homeland/public/robots.txt
    command: bundle exec puma -C config/puma-master.rb
    ports:
      - "7000:7000"

  app_backup:
    <<: *app_base
    container_name: 'homeland_app_backup'
    command: bundle exec puma -C config/puma-backup.rb
    ports:
      - "7001:7001"

  worker:
    <<: *app_base
    container_name: 'homeland_worker'
    ports: []
    command: bundle exec sidekiq -C config/sidekiq.yml -L /home/app/log/sidekiq.log

  web:
    <<: *app_base
    container_name: 'homeland_web'
    links:
      - app
      - app_backup
      - worker
    command: /etc/nginx/start
    ports:
      - "80:80"
      - "443:443"
